defaults: &defaults
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 10
  username: user
  host: localhost

development:
  <<: *defaults
  database: app-dev
  

 

test:
  <<: *defaults
  database: cukcuk_testing

staging:
  <<: *defaults
  database: cukcuk_staging
  password: appstone

production:
  <<: *defaults
  database: cukcuk
  password: appstone
